# Generated by Django 3.1 on 2020-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200808_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='bought',
            field=models.IntegerField(null=True),
        ),
    ]
