# Generated by Django 3.1 on 2020-08-23 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_auto_20200823_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='items',
            new_name='id_service',
        ),
        migrations.AddField(
            model_name='basket',
            name='ilosc',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
